import {
  Vendor,
  Venue,
  Appearance,
  Source,
  Observation,
  ExtractionCandidate,
  Menu,
} from '@/types';
import { getDateLA } from '../timezone';

const nowIso = new Date().toISOString();

export const INITIAL_DEMO_VENDORS: Vendor[] = [
  {
    id: 'vendor-galvans-demo',
    slug: 'demo-galvans-eatery',
    name: "Demo Galvan's Eatery (Demo)",
    isDemo: true,
    heroImage: 'https://images.unsplash.com/photo-1565123409695-7b5ef63a2efb?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1565123409695-7b5ef63a2efb?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?auto=format&fit=crop&w=1000&q=80',
    ],
    vendorType: 'taco_stand',
    cuisines: ['Tacos & Mexican'],
    description: 'Authentic gourmet tacos, burritos, and handcrafted fresh salsas made daily in Sonoma County.',
    priceRange: '$$',
    dietaryTags: ['vegetarian', 'gluten_free'],
    websiteUrl: 'https://example.com/demo-galvans',
    instagramUrl: 'https://instagram.com/demo_galvans_eatery',
    facebookUrl: 'https://facebook.com/demogalvanseatery',
    orderingUrl: 'https://example.com/demo-galvans/order',
    cateringInfo: 'Available for private events and brewery pop-ups. Contact demo@example.com',
    menuId: 'menu-galvans-demo',
    favoriteCount: 42,
    lastScheduleUpdate: nowIso,
    createdAt: nowIso,
    updatedAt: nowIso,
  },
  {
    id: 'vendor-redwood-bbq-demo',
    slug: 'demo-redwood-bbq',
    name: 'Demo Redwood Smoked BBQ (Demo)',
    isDemo: true,
    heroImage: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=1000&q=80',
    ],
    vendorType: 'trailer',
    cuisines: ['Smoked BBQ'],
    description: 'Slow-smoked brisket, pulled pork, and oak-fired ribs served with signature apple cider coleslaw.',
    priceRange: '$$',
    dietaryTags: ['gluten_free'],
    websiteUrl: 'https://example.com/demo-redwood-bbq',
    instagramUrl: 'https://instagram.com/demo_redwood_bbq',
    favoriteCount: 29,
    lastScheduleUpdate: nowIso,
    createdAt: nowIso,
    updatedAt: nowIso,
  },
  {
    id: 'vendor-sonoma-pizza-demo',
    slug: 'demo-sonoma-pizza-co',
    name: 'Demo Sonoma Wood-Fired Pizza (Demo)',
    isDemo: true,
    heroImage: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1000&q=80',
    ],
    vendorType: 'mobile_pizza',
    cuisines: ['Wood-Fired Pizza'],
    description: 'Neapolitan artisanal pizzas baked in a mobile 900° wood-fired oven using locally sourced cheeses and produce.',
    priceRange: '$$$',
    dietaryTags: ['vegetarian', 'vegan'],
    websiteUrl: 'https://example.com/demo-sonoma-pizza',
    favoriteCount: 56,
    lastScheduleUpdate: nowIso,
    createdAt: nowIso,
    updatedAt: nowIso,
  },
  {
    id: 'vendor-green-bowls-demo',
    slug: 'demo-organic-green-bowls',
    name: 'Demo Organic Green Bowls (Demo)',
    isDemo: true,
    heroImage: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1000&q=80',
    images: [
      'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1000&q=80',
    ],
    vendorType: 'food_truck',
    cuisines: ['Vegan & Organic'],
    description: '100% plant-based nourish bowls, acai bowls, cold-pressed juices, and gluten-free wraps.',
    priceRange: '$$',
    dietaryTags: ['vegetarian', 'vegan', 'gluten_free'],
    websiteUrl: 'https://example.com/demo-green-bowls',
    favoriteCount: 19,
    lastScheduleUpdate: nowIso,
    createdAt: nowIso,
    updatedAt: nowIso,
  },
];

export const INITIAL_DEMO_VENUES: Venue[] = [
  {
    id: 'venue-henhouse-demo',
    slug: 'demo-henhouse-brewing-santa-rosa',
    canonicalName: 'Demo HenHouse Tasting Room (Demo)',
    address: '3229 Bellevue Ave',
    city: 'Santa Rosa',
    lat: 38.4315,
    lng: -122.7214,
    websiteUrl: 'https://example.com/demo-henhouse',
    photoUrl: 'https://images.unsplash.com/photo-1555658636-6e4a36218be7?auto=format&fit=crop&w=1000&q=80',
    aliases: ['Demo HenHouse', 'Demo Hen House Brewing', 'HenHouse Santa Rosa Demo'],
    status: 'active',
    isDemo: true,
    createdAt: nowIso,
    updatedAt: nowIso,
  },
  {
    id: 'venue-cooperage-demo',
    slug: 'demo-cooperage-brewing',
    canonicalName: 'Demo Cooperage Brewing Company (Demo)',
    address: '981 Airway Ct',
    city: 'Santa Rosa',
    lat: 38.455,
    lng: -122.73,
    websiteUrl: 'https://example.com/demo-cooperage',
    photoUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1000&q=80',
    aliases: ['Demo Cooperage', 'Cooperage Beer Demo'],
    status: 'active',
    isDemo: true,
    createdAt: nowIso,
    updatedAt: nowIso,
  },
  {
    id: 'venue-petaluma-plaza-demo',
    slug: 'demo-petaluma-river-plaza',
    canonicalName: 'Demo Petaluma River Plaza (Demo)',
    address: '100 Petaluma Blvd N',
    city: 'Petaluma',
    lat: 38.2324,
    lng: -122.6366,
    websiteUrl: 'https://example.com/demo-petaluma-plaza',
    aliases: ['Petaluma Plaza Demo', 'Petaluma Riverfront'],
    status: 'active',
    isDemo: true,
    createdAt: nowIso,
    updatedAt: nowIso,
  },
  {
    id: 'venue-barlow-demo',
    slug: 'demo-sebastopol-barlow-center',
    canonicalName: 'Demo Sebastopol Barlow Center (Demo)',
    address: '6770 McKinley St',
    city: 'Sebastopol',
    lat: 38.4005,
    lng: -122.8228,
    websiteUrl: 'https://example.com/demo-barlow',
    aliases: ['The Barlow Demo', 'Barlow District'],
    status: 'active',
    isDemo: true,
    createdAt: nowIso,
    updatedAt: nowIso,
  },
  {
    id: 'venue-healdsburg-square-demo',
    slug: 'demo-healdsburg-plaza',
    canonicalName: 'Demo Healdsburg Plaza (Demo)',
    address: 'Matheson St & Plaza St',
    city: 'Healdsburg',
    lat: 38.6103,
    lng: -122.8692,
    aliases: ['Healdsburg Town Square Demo'],
    status: 'active',
    isDemo: true,
    createdAt: nowIso,
    updatedAt: nowIso,
  },
];

const today = getDateLA(0);
const tomorrow = getDateLA(1);
const dayAfter = getDateLA(2);
const inFourDays = getDateLA(4);
const inSevenDays = getDateLA(7);

export const INITIAL_DEMO_APPEARANCES: Appearance[] = [
  {
    id: 'app-1',
    vendorId: 'vendor-galvans-demo',
    venueId: 'venue-henhouse-demo',
    date: today,
    startTime: '16:00',
    endTime: '20:00',
    status: 'scheduled',
    isPublished: true,
    isManualOverride: false,
    observationIds: ['obs-1'],
    notes: 'Brewery patio appearance',
    createdBy: 'admin-seed',
    updatedBy: 'admin-seed',
    createdAt: nowIso,
    updatedAt: nowIso,
  },
  {
    id: 'app-2',
    vendorId: 'vendor-redwood-bbq-demo',
    venueId: 'venue-cooperage-demo',
    date: today,
    startTime: '12:00',
    endTime: '19:00',
    status: 'scheduled',
    isPublished: true,
    isManualOverride: true,
    observationIds: [],
    notes: 'Smoked meats special event',
    createdBy: 'admin-seed',
    updatedBy: 'admin-seed',
    createdAt: nowIso,
    updatedAt: nowIso,
  },
  {
    id: 'app-3',
    vendorId: 'vendor-sonoma-pizza-demo',
    venueId: 'venue-barlow-demo',
    date: today,
    startTime: '17:00',
    endTime: '21:00',
    status: 'scheduled',
    isPublished: true,
    isManualOverride: false,
    observationIds: ['obs-2'],
    notes: 'Friday night wood-fired pizza',
    createdBy: 'admin-seed',
    updatedBy: 'admin-seed',
    createdAt: nowIso,
    updatedAt: nowIso,
  },
  {
    id: 'app-4',
    vendorId: 'vendor-green-bowls-demo',
    venueId: 'venue-petaluma-plaza-demo',
    date: tomorrow,
    startTime: '11:00',
    endTime: '15:00',
    status: 'scheduled',
    isPublished: true,
    isManualOverride: false,
    observationIds: [],
    createdBy: 'admin-seed',
    updatedBy: 'admin-seed',
    createdAt: nowIso,
    updatedAt: nowIso,
  },
  {
    id: 'app-5',
    vendorId: 'vendor-galvans-demo',
    venueId: 'venue-healdsburg-square-demo',
    date: dayAfter,
    startTime: '16:00',
    endTime: '20:00',
    status: 'scheduled',
    isPublished: true,
    isManualOverride: false,
    observationIds: [],
    createdBy: 'admin-seed',
    updatedBy: 'admin-seed',
    createdAt: nowIso,
    updatedAt: nowIso,
  },
  {
    id: 'app-6',
    vendorId: 'vendor-redwood-bbq-demo',
    venueId: 'venue-barlow-demo',
    date: inFourDays,
    startTime: '12:00',
    endTime: '18:00',
    status: 'scheduled',
    isPublished: true,
    isManualOverride: false,
    observationIds: [],
    createdBy: 'admin-seed',
    updatedBy: 'admin-seed',
    createdAt: nowIso,
    updatedAt: nowIso,
  },
  {
    id: 'app-7',
    vendorId: 'vendor-sonoma-pizza-demo',
    venueId: 'venue-henhouse-demo',
    date: inSevenDays,
    startTime: '16:30',
    endTime: '20:30',
    status: 'scheduled',
    isPublished: true,
    isManualOverride: false,
    observationIds: [],
    createdBy: 'admin-seed',
    updatedBy: 'admin-seed',
    createdAt: nowIso,
    updatedAt: nowIso,
  },
];

export const INITIAL_DEMO_SOURCES: Source[] = [
  {
    id: 'source-galvans-insta-demo',
    entityType: 'vendor',
    entityId: 'vendor-galvans-demo',
    purpose: 'schedule',
    sourceType: 'instagram',
    url: 'https://instagram.com/demo_galvans_eatery',
    name: "Demo Galvan's Instagram Feed",
    enabled: true,
    priority: 'high',
    checkFrequencyHours: 12,
    parserType: 'social_post_extractor',
    lastCheckedAt: nowIso,
    lastSuccessfulAt: nowIso,
    createdAt: nowIso,
    updatedAt: nowIso,
  },
  {
    id: 'source-henhouse-web-demo',
    entityType: 'venue',
    entityId: 'venue-henhouse-demo',
    purpose: 'schedule',
    sourceType: 'website',
    url: 'https://example.com/demo-henhouse/events',
    name: 'Demo HenHouse Food Truck Calendar',
    enabled: true,
    priority: 'high',
    checkFrequencyHours: 24,
    parserType: 'html_calendar_parser',
    lastCheckedAt: nowIso,
    lastSuccessfulAt: nowIso,
    createdAt: nowIso,
    updatedAt: nowIso,
  },
  {
    id: 'source-failing-demo',
    entityType: 'vendor',
    entityId: 'vendor-redwood-bbq-demo',
    purpose: 'schedule',
    sourceType: 'website',
    url: 'https://example.com/broken-link-demo',
    name: 'Demo Redwood BBQ Broken Feed',
    enabled: true,
    priority: 'low',
    checkFrequencyHours: 48,
    parserType: 'rss_parser',
    lastCheckedAt: nowIso,
    lastError: 'HTTP 404 Not Found (Preserving previous verified schedule)',
    createdAt: nowIso,
    updatedAt: nowIso,
  },
];

export const INITIAL_DEMO_CANDIDATES: ExtractionCandidate[] = [
  {
    id: 'cand-1',
    sourceId: 'source-galvans-insta-demo',
    vendorId: 'vendor-galvans-demo',
    rawText: "This Friday we'll be slinging fresh tacos at HenHouse Santa Rosa from 4pm to 8pm! Come get your taco fix 🌮🍺",
    proposedVenueText: 'HenHouse Santa Rosa',
    matchedVenueId: 'venue-henhouse-demo',
    date: today,
    startTime: '16:00',
    endTime: '20:00',
    confidenceScore: 0.92,
    validationWarnings: [],
    hasConflicts: false,
    observationIds: ['obs-cand-1'],
    status: 'pending',
    createdAt: nowIso,
  },
  {
    id: 'cand-2',
    sourceId: 'source-galvans-insta-demo',
    vendorId: 'vendor-galvans-demo',
    rawText: "Saturday night catch us at Cooperage Beer from 5 to 9pm!",
    proposedVenueText: 'Cooperage Beer',
    matchedVenueId: 'venue-cooperage-demo',
    date: tomorrow,
    startTime: '17:00',
    endTime: '21:00',
    confidenceScore: 0.78,
    validationWarnings: ['Venue name matched via alias "Cooperage Beer"'],
    hasConflicts: true,
    conflictNotes: 'Source observation overlaps with another tentative posting',
    observationIds: ['obs-cand-2'],
    status: 'pending',
    createdAt: nowIso,
  },
];

export const INITIAL_DEMO_MENUS: Menu[] = [
  {
    id: 'menu-galvans-demo',
    vendorId: 'vendor-galvans-demo',
    mode: 'structured',
    updatedAt: nowIso,
    items: [
      {
        id: 'item-1',
        menuId: 'menu-galvans-demo',
        category: 'Tacos',
        name: 'Birria QuesaTaco',
        description: 'Slow-cooked braised beef with melted cheese, cilantro, onions, and side of consommé dipping broth.',
        price: 5.5,
        dietaryTags: ['gluten_free'],
        isAvailable: true,
      },
      {
        id: 'item-2',
        menuId: 'menu-galvans-demo',
        category: 'Tacos',
        name: 'Charred Veggie & Avocado Taco',
        description: 'Grilled zucchini, roasted corn, black beans, cotija cheese, and house avocado salsa.',
        price: 4.75,
        dietaryTags: ['vegetarian', 'gluten_free'],
        isAvailable: true,
      },
      {
        id: 'item-3',
        menuId: 'menu-galvans-demo',
        category: 'Sides',
        name: 'Fresh Chips & Guacamole',
        description: 'House-made warm tortilla chips served with freshly mashed lime avocado guacamole.',
        price: 6.0,
        dietaryTags: ['vegetarian', 'vegan', 'gluten_free'],
        isAvailable: true,
      },
    ],
  },
];
